import { library } from "@fortawesome/fontawesome-svg-core";
import { faAngleDoubleLeft, faAngleDoubleRight, faArrowRightFromBracket, faBars, faChevronRight, faCodeBranch, faEllipsisV, faEye, faFlagCheckered, faGlobe, faImages, faLocationDot, faMapMarked, faMapPin, faPenToSquare, faPiggyBank, faSitemap, faTags, faTrash, faUser, faUserCheck, faUserGroupCrown, faUsersCrown, faUsers, faClock, faMemo, faCircleInfo, faClipboardCheck, faMagnifyingGlass } from "@fortawesome/pro-duotone-svg-icons";
import { faHome, faScrubber } from '@fortawesome/pro-regular-svg-icons';
import { faPlus, faTimes } from "@fortawesome/pro-solid-svg-icons";

library.add(faScrubber);
library.add(faUsers);
library.add(faHome);
library.add(faArrowRightFromBracket);
library.add(faCodeBranch);
library.add(faBars);
library.add(faUser);
library.add(faTrash);
library.add(faPenToSquare);
library.add(faPlus);
library.add(faTags);
library.add(faEllipsisV);
library.add(faAngleDoubleRight);
library.add(faAngleDoubleLeft);
library.add(faAngleDoubleLeft);
library.add(faMapPin);
library.add(faChevronRight);
library.add(faFlagCheckered);
library.add(faUserCheck);
library.add(faMapMarked);
library.add(faPiggyBank);
library.add(faGlobe);
library.add(faSitemap);
library.add(faUserGroupCrown);
library.add(faUsersCrown);
library.add(faLocationDot);
library.add(faImages);
library.add(faTimes);
library.add(faEye);
library.add(faClock);
library.add(faMemo);
library.add(faCircleInfo);
library.add(faClipboardCheck);
library.add(faMagnifyingGlass);